disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ball & Train | IB Sports Academy"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Ball & Train | Basketball Now & Forever"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Ishwar Bhati"
  email = "academyibsports@gmail.com"
  image = "profile_pic.png"
#   imageQuality = 96
  headline = "Building Ballers | Shaping Futures"
  bio = "Basketball Now & Forever"
  links = [
    { whatsapp = "https://wa.me/918860500059" },
    { email = "mailto:academyibsports@gmail.com" },
    { youtube = "https://www.youtube.com/@IBSportsAcademy" },
    { link = "https://ibsportsacademy.com/" },
    { facebook = "https://www.facebook.com/ibsportsacademy/" },
    { instagram = "https://www.instagram.com/ibsportsacademy/" },
    { linkedin = "https://www.linkedin.com/company/ib-sports-academy/" },
    { x-twitter = "https://x.com/ibsportsacademy" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://ibsportsacademy.github.io/blog/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
  ]
